'use client'

import { useState } from 'react'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/Card'
import { Button } from '@/components/ui/Button'
import { GradientHeading } from '@/components/ui/GradientHeading'
import { Section } from '@/components/motion/Section'
import { FileCode, Play, Trash2, Check, Copy, Loader2, Sparkles, Terminal } from 'lucide-react'

export default function SVGOptimizerPage() {
  const [svg, setSvg] = useState('')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState<string | null>(null)
  const [copied, setCopied] = useState(false)

  const handleOptimize = () => {
    if (!svg.trim()) return
    setLoading(true)
    setResult(null)

    setTimeout(() => {
      // Basic client-side SVG optimization rules: remove comments, xml declarations, double spaces
      let optimized = svg
        .replace(/<!--[\s\S]*?-->/g, '') // remove comments
        .replace(/<\?xml[\s\S]*?\?>/g, '') // remove xml declarations
        .replace(/\s+/g, ' ') // collapse whitespaces
        .replace(/>\s+</g, '><') // remove whitespace between tags
        .trim()

      setResult(optimized)
      setLoading(false)
    }, 1000)
  }

  const handleClear = () => {
    setSvg('')
    setResult(null)
  }

  const handleLoadSample = () => {
    setSvg(`<!-- Generated by Graphic App -->\n<?xml version="1.0" encoding="utf-8"?>\n<svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" viewBox="0 0 100 100">\n  <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />\n</svg>`)
  }

  const handleCopy = async () => {
    if (!result) return
    try {
      await navigator.clipboard.writeText(result)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch (_) {}
  }

  return (
    <div className="space-y-8">
      {/* Title */}
      <Section delay={0.05}>
        <div className="space-y-2">
          <div className="text-xs text-primary font-semibold tracking-widest uppercase">Pillar 2: Utilities</div>
          <GradientHeading as="h1" className="text-3xl sm:text-4xl">SVG Code Optimizer</GradientHeading>
          <p className="text-muted-foreground text-xs sm:text-sm">
            Minify SVG file components by cleaning comments, XML schemas, and double spacings parameters.
          </p>
        </div>
      </Section>

      {/* Grid */}
      <Section delay={0.1}>
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">
          {/* Inputs */}
          <div className="lg:col-span-5 space-y-4">
            <Card className="flex flex-col h-[280px]">
              <CardHeader className="flex flex-row items-center justify-between border-b border-border/40 py-2.5 bg-secondary/15">
                <span className="text-xs font-semibold text-foreground/80 flex items-center gap-1.5 font-mono">
                  <Terminal className="h-3.5 w-3.5 text-violet-500" />
                  RAW_SVG_MARKUP_INPUT
                </span>
                <div className="flex gap-2">
                  <Button variant="ghost" size="sm" className="h-6 text-[10px] px-2" onClick={handleLoadSample}>
                    Sample
                  </Button>
                  <Button variant="ghost" size="sm" className="h-6 text-[10px] px-2 text-destructive hover:bg-destructive/10" onClick={handleClear}>
                    Clear
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="flex-1 p-0">
                <textarea
                  value={svg}
                  onChange={(e) => setSvg(e.target.value)}
                  placeholder="Paste raw SVG tags code here..."
                  className="w-full h-full p-4 font-mono text-xs bg-transparent border-0 outline-none resize-none text-foreground placeholder-muted-foreground/40 leading-relaxed"
                  spellCheck="false"
                />
              </CardContent>
            </Card>

            <Button
              onClick={handleOptimize}
              disabled={loading || !svg.trim()}
              className="w-full h-10 text-xs font-semibold"
            >
              {loading ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Optimizing SVG...
                </>
              ) : (
                <>
                  <Sparkles className="mr-2 h-4 w-4 text-amber-400" />
                  Optimize SVG Tags
                </>
              )}
            </Button>
          </div>

          {/* Outputs */}
          <div className="lg:col-span-7 space-y-4">
            {result && (
              <Card className="p-4 flex items-center justify-center border border-emerald-500/20 bg-emerald-500/5 h-[100px] rounded-xl overflow-hidden">
                <div dangerouslySetInnerHTML={{ __html: result }} className="w-16 h-16 flex items-center justify-center" />
              </Card>
            )}

            {result ? (
              <Card className="border-border/40 bg-card/60">
                <CardHeader className="flex flex-row items-center justify-between border-b border-border/40 py-2.5 bg-secondary/15">
                  <span className="text-xs font-semibold text-foreground/80 flex items-center gap-1.5 font-mono">
                    <FileCode className="h-3.5 w-3.5 text-emerald-500" />
                    OPTIMIZED_SVG_OUTPUT
                  </span>
                  <Button variant="secondary" size="sm" className="h-6 text-[10px] px-2.5" onClick={handleCopy}>
                    {copied ? <Check className="h-3.5 w-3.5 mr-1 text-emerald-500" /> : <Copy className="h-3.5 w-3.5 mr-1" />}
                    Copy Code
                  </Button>
                </CardHeader>
                <CardContent className="p-4 bg-black/10">
                  <pre className="font-mono text-xs text-emerald-400 leading-relaxed overflow-x-auto whitespace-pre-wrap max-h-[220px]">
                    <code>{result}</code>
                  </pre>
                </CardContent>
              </Card>
            ) : (
              <div className="border border-dashed border-border/60 rounded-xl h-[280px] flex flex-col items-center justify-center text-center text-muted-foreground space-y-2 p-6">
                <FileCode className="h-8 w-8 text-muted-foreground/30 animate-pulse" />
                <p className="text-sm font-semibold text-foreground/80">Pending SVG Input</p>
                <p className="text-xs max-w-sm">
                  Paste unoptimized XML coordinates vector tags on the left.
                </p>
              </div>
            )}
          </div>
        </div>
      </Section>
    </div>
  )
}
